const throwError = () => {
  throw new Error("This is my error another, random test!!!");
};

export default throwError;
